# Generated by Django 4.2.1 on 2023-05-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=32)),
                ('genero', models.CharField(max_length=32)),
                ('ciudad', models.CharField(max_length=256)),
                ('distrito', models.CharField(max_length=256)),
                ('codigo_postal', models.CharField(default='15494', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('apellido', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('dni', models.CharField(max_length=32)),
                ('genero', models.CharField(max_length=32)),
                ('cargo', models.CharField(max_length=256)),
                ('turno', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=256)),
                ('diseno', models.CharField(max_length=256)),
                ('empaque', models.CharField(max_length=256)),
                ('categoria', models.CharField(max_length=256)),
                ('genero', models.CharField(max_length=256)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagenInstrumento', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
        ),
    ]
