# Generated by Django 4.2.1 on 2023-05-26 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='comentarios_producto',
        ),
    ]
