# Generated by Django 4.2.1 on 2023-05-27 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_productos', '0002_remove_producto_comentarios_producto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagenInstrumento',
            new_name='imagenProducto',
        ),
    ]
