# Generated by Django 4.2.1 on 2023-05-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_productos', '0003_rename_imageninstrumento_producto_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagenes/'),
        ),
    ]
